[package]
name = "slice_type"
version = "0.1.0"
authors = ["Ryan Fujiwara <ryan@uppluck.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
